[advisories]
ignore = [
    "RUSTSEC-2023-0071", # Marvin Attack (rsa), no fix available, unused database driver (sqlx-mysql)
    "RUSTSEC-2024-0363", # Binary Protocol Misinterpretation (sqlx), unused database drivers (postgres/mysql)
    "RUSTSEC-2026-0098", # Name constraints for URI names (rustls-webpki)
    "RUSTSEC-2026-0099", # Name constraints wildcard (rustls-webpki)
    "RUSTSEC-2026-0104", # CRL parsing panic (rustls-webpki)
]
